### ISSUE TITLE
IGDB search is missing results shown on the main site and other bots

### ISSUE THREAD

**Issue by rogersachan** [Favna/ribbon#247]
**Please describe the problem you are having in as much detail as possible:**
Certain games refuse to show up using the `!igdb` command despite being searchable with the [reference bot](https://gitlab.com/SirRandall/Bender) (located in the IGDB server) and the [main search page](https://www.igdb.com/search).

**Include a reproduction steps and screenshots here, if possible:**
![image](https://user-images.githubusercontent.com/7173984/69029283-7d507c00-09a2-11ea-8ff3-41c4c40af5e3.png)

![image](https://user-images.githubusercontent.com/7173984/69029345-a83ad000-09a2-11ea-942c-d8069b54e77d.png)

![image](https://user-images.githubusercontent.com/7173984/69029409-d6201480-09a2-11ea-8399-211e3ec72d2a.png)

**Further details:**
- Server name or ID: 644347229959618576
- Username and tag: (in screenshot)
- Priority this issue should have – please be realistic and elaborate if possible: 🤷‍♂️

**Comment by Favna** [comment]
Thanks for reporting this. I recently announced through the support server however that Ribbon will soon (December 1st) stop being hosted and has already stopped development. That said, I will look into this however not for Ribbon but rather for Skyra. I strongly recommend you invite Skyra to your server which has tonnes of more, and better, features than Ribbon. https://skyra.pw

Full announcement here:

![image](https://user-images.githubusercontent.com/4019718/69029920-83605000-09d6-11ea-9d25-e9ac57d4c0f6.jpg)

**Comment by rogersachan** [comment]
Looks like this is a bug in the skyra implementation as well, going to create a similar issue over there.

**Comment by Favna** [comment]
Yeah skyra's implementation is pretty much a 1:1 copy of Ribbon's. Wrote it myself. Thanks for creating an issue there, I'll close this one and we'll be picking it up there.
